# Generated by Django 5.1.1 on 2024-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_leader', models.CharField(max_length=255)),
                ('leader_contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=255)),
                ('member1', models.CharField(blank=True, max_length=255, null=True)),
                ('member1_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('member2', models.CharField(blank=True, max_length=255, null=True)),
                ('member2_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('member3', models.CharField(blank=True, max_length=255, null=True)),
                ('member3_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('member4', models.CharField(blank=True, max_length=255, null=True)),
                ('member4_contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
